use_frameworks!

platform :ios, '8.0'

target 'IDaaSBoLiSDK_Example' do
  pod 'IDaaSBoLiSDK', :path => '../'

  target 'IDaaSBoLiSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
